
-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 14:14:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojabd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lojabd` ;

-- -----------------------------------------------------
-- Schema lojabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojabd` DEFAULT CHARACTER SET utf8mb3 ;
USE `lojabd` ;

-- -----------------------------------------------------
-- Table `lojabd`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lojabd`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `lojabd`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



INSERT INTO `lojabd`.`Usuario` (`nome`, `email`, `senha`)
VALUES ('João Silva', 'joao.silva@email.com', 'senha123');


-- -----------------------------------------------------
-- Table `lojabd`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lojabd`.`produto` ;

CREATE TABLE IF NOT EXISTS `lojabd`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sessao` VARCHAR(20) NOT NULL,
  `nome_do_produto` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `foto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabd`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lojabd`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `lojabd`.`carrinho` (
  `usuario_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  INDEX `fk_carrinho_Usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_carrinho_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `lojabd`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `lojabd`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabd`.`produto_unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lojabd`.`produto_unidade` ;

CREATE TABLE IF NOT EXISTS `lojabd`.`produto_unidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_unidade_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_unidade_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `lojabd`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from Usuario;
